name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Compute parameters
      id: compute
      run: |
        BUNDLENAME=criu-crac-build-${{ github.run_number }}
        for i in BUNDLENAME; do
          echo "::set-output name=${i}::${!i}"
        done

    - name: Start build container
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com;
        docker run -d --name build
        -w $PWD
        -v /home/runner:/home/runner
        -u $(id -u):$(id -g)
        --entrypoint tail
        docker.pkg.github.com/crac/docker-build/image:latest
        -f /dev/null
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - run: make DESTDIR=. PREFIX=/${{ steps.compute.outputs.BUNDLENAME }} install-criu V=1
      shell: docker exec build bash -e {0}

    - run: tar -zcf ${{ steps.compute.outputs.BUNDLENAME }}.tar.gz ${{ steps.compute.outputs.BUNDLENAME }}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.compute.outputs.BUNDLENAME }}
        path: ${{ steps.compute.outputs.BUNDLENAME }}.tar.gz

