name: Build

on:
  push:
    branches: [ crac ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: docker exec build bash -e {0}
    steps:
    - run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
    - run:  docker pull docker.pkg.github.com/org-crac/docker-build/image:latest
      shell: bash
    - name: Start build container
      run: docker run -d --name build
        -w $PWD
        -v /home/runner:/home/runner
        --entrypoint tail
        docker.pkg.github.com/org-crac/docker-build/image:latest
        -f /dev/null
      shell: bash

    - uses: actions/checkout@v2
    - run: make DESTDIR=. PREFIX=/criu-dist install-criu V=1
    - run: tar -zcf criu-dist.tar.gz criu-dist
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-crac
        release_name: Release crac
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./criu-dist.tar.gz
        asset_name: criu-dist.tar.gz
        asset_content_type: application/gzip
